---

- name: Installing Iterm2.
  community.general.homebrew_cask:
    name: iterm2
    state: installed
  when: ansible_system == "Darwin"
  notify:
    - Install DynamicRole
    - Integrate Shell

- name: Ensure that iTerm2 DynamicProfiles directory exists.
  ansible.builtin.file:
    path: "{{ iterm2_profile_directory }}"
    state: directory
    mode: '0755'
    owner: "{{ remote_regular_user }}"
