---

- name: Tap a Homebrew repository, for fonts on OSX
  community.general.homebrew_tap:
    name: homebrew/cask-fonts
  when: ansible_system == "Darwin"

- name: Ensure Powerline Fonts are installed on OSX.
  block:
    - name: Installing Dependencies - Nerd Font Fira Code for Powerline.
      community.general.homebrew_cask:
        name: font-fira-mono-for-powerline
        state: present
      when: ansible_system == "Darwin"
      ignore_errors: true
