---

- name: Fonts - Tap a Homebrew repository, for fonts on macOS.
  community.general.homebrew_tap:
    name: homebrew/cask-fonts
  when: ansible_system == "Darwin"

- name: Fonts - Ensure Powerline Fonts are installed on macOS.
  block:
    - name: Installing Dependencies - Custom Fonts
      community.general.homebrew_cask:
        name: "{{ iterm2_font }}"
        state: present
      when: ansible_system == "Darwin"
      ignore_errors: true
