---

# Make sure zsh is installed and set to the user's default shell.
- include_tasks: zsh.yml
  tags:
    - zsh

# Install iTerm2 if system is macOS.
- include_tasks: install-iterm2.yml
  tags:
    - iterm2

# Install Powerline Fonts.
- include_tasks: install-fonts.yml
  tags:
    - fonts

# Install oh-my-zsh.
- include_tasks: install-omz.yml
  tags:
    - omz

# Install Spaceship Theme.
- include_tasks: install-spaceship.yml
  tags:
    - spaceship
