---
- name: Zsh - Establish home directory.
  ansible.builtin.set_fact:
    zsh_user_home_dir: "{{ (ansible_system == 'Darwin') | ternary('Users', 'home') }}"

- name: Zsh - Ensure package is installed.
  block:
    - name: Install zsh for Linux.
      ansible.builtin.package:
        name: "zsh"
        state: present
      when: ansible_system == "Linux"

    - name: Install zsh for macOS.
      community.general.homebrew:
        name: zsh
        state: present
        update_homebrew: true
      when: ansible_system == "Darwin"

- name: Zsh - Locate binary path.
  ansible.builtin.command: "which zsh"
  register: zsh_installed_path
  changed_when: false

- name: Zsh - Set user shell to zsh.
  ansible.builtin.user:
    name: "{{ remote_regular_user }}"
    shell: "{{ zsh_installed_path.stdout }}"
  when: ansible_system != 'Darwin'
